version: '3'

services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    networks:
      - local_dev
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass

  web:
    volumes:
      - "db_data:/var/lib/mysql/data"
      - "./php/src:/var/www/html"
      - "./backup:/mnt/backup"
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - local_dev

networks:
  local_dev:

volumes:
  app_data: 
  db_data: 
